const version = require('./package.json').version;
const exec = require('child_process').spawnSync;
exec('git', ['add', '.']);
exec('git', ['commit', '-m', `feat: v${version}`]);
console.log(`commit success: feat: v${version}`);
exec('git', ['tag', `v${version}`]);
console.log(`new tag: v${version}`);
exec('git', ['push']);
exec('git', ['push', 'origin', `v${version}`]);
console.log('代码已提交到远程');
